ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}
#
ARG PUID=1000
ARG PGID=1000
#
ENV TTRSS_SRC="/opt/ttrss/ttrss.zip"
#
RUN set -xe \
    && apk add --no-cache --purge -uU \
        curl \
        unzip \
	    php7-apcu \
	    php7-curl \
	    php7-dom \
	    php7-fileinfo \
	    php7-gd \
	    php7-iconv \
	    php7-intl \
	    php7-mysqli \
	    php7-mysqlnd \
	    php7-pcntl \
	    php7-pdo_mysql \
	    php7-pdo_pgsql \
	    php7-pgsql \
	    php7-posix \
	    php7-zlib \
        php7-session \
    && mkdir -p /opt/ttrss \
    && curl -o ${TTRSS_SRC} -SL "https://git.tt-rss.org/git/tt-rss/archive/master.tar.gz" \
    && rm -rf /var/cache/apk/* /tmp/*
# add local files
COPY root/ /
# ports, volumes etc from nginx
# ENTRYPOINT ["/init"]
